# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
      
    - name: Run Tests
      run: mvn -B -Dmaven.test.failure.ignore=true test
      
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: JUnit Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: false

    - name: Checkstyle for Java
      uses: dbelyaev/action-checkstyle@v0.6.1
      with:
        checkstyle_config: checkstyle.xml
        reporter: github-check
        level: warning
        workdir: src
